### ISSUE TITLE
getData() returns call to undefined method  /Lead::getData() 

### ISSUE THREAD

**Issue by phillypro** [loopline-systems/closeio-api-wrapper#25]
as of the last two weeks  

an error has popped up i redownloaded the package to get any updates you might have added

    $response     = $leadsApi->addLead($lead);
    $responsedata = $response->getData();

using getData()  is throwing an undefined method error.....even tho i see the function in the CloseIoRequest.php

**Comment by audvin** [comment]
I see the same new error here. True for both `$response->getData();` and `$response->getRawData()`

**Comment by phillypro** [comment]
Yea its crippled me

**Comment by null9beta** [comment]
@phillypro @audvin hey guys, sry for the late reply. Due to the christmas break we all were at our families i guess and hope :)

We gonna look into the report as soon as possible. I`ll updated you here when we found the issue.

**Comment by mickadoo** [comment]
@phillypro With the release of v0.4 @marczahn changed `$leadsApi->addLead($lead)` to return an instance of a Lead instead of a CloseIoResponse. 

This was the right thing to do in my opinion because all other methods in the LeadApi return either a Lead or an array of Leads and returning a CloseIoResponse for just one is inconsistent.

Sorry for the breaking changes, but hopefully we'll have a more consistent interface throughout the wrapper in the future.
